// vue-flopper/src/App.vue

<script setup lang="ts">
    import NavBar from './components/NavBar.vue'
    import Config from './components/Config.vue'
    import { useStore } from './store';
    const store = useStore();
</script>

<template>
    <NavBar />
     
    <div v-show="store.mainPanel === 'config'">
        <Config />
    </div>

</template>

// flopper/src/App.tsx
import "./index.css";
import { useState } from "react";
import Navbar from "./components/Navbar";
import Config from "./components/Config";

function App() {

    const [panel, setPanel] = useState("config");

    return (
        <>
            <Navbar setPanel={setPanel} />
            <div>
                { panel === "config" ? <Config /> : <Config /> }
            </div>
        </>
    )
}

export default App;
